### ISSUE TITLE
TypeError: add_weight() got multiple values for argument 'name'

### ISSUE THREAD

**Issue by ouening** [ShawnyXiao/TextClassification-Keras#5]
Attention类实现感觉有问题,本人使用TextBiRNN模型来跑,出现以下错误:
<pre>Traceback (most recent call last):
  File &quot;train.py&quot;, line 86, in &lt;module&gt;
    last_activation=&apos;softmax&apos;).get_model()
  File &quot;/media/gaoya/disk/Applications/keras/短文本分类/model.py&quot;, line 282, in get_model
    x_word = Attention(self.maxlen_word)(x_word)
  File &quot;/media/gaoya/disk/Applications/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py&quot;, line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File &quot;/media/gaoya/disk/Applications/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py&quot;, line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File &quot;/media/gaoya/disk/Applications/keras/短文本分类/model.py&quot;, line 231, in build
    constraint=self.b_constraint)
TypeError: add_weight() got multiple values for argument &apos;name&apos;
</pre>

请问怎么解决呢

**Comment by ShawnyXiao** [comment]
这可能是 Keras 升级了 API 导致的，你可以查一下最新的 API，相应的修改一下参数即可

**Comment by zhouzuguang** [comment]
self.W = self.add_weight(shape=(input_shape[-1], input_shape[-1],),
                                 initializer=self.init,
                                 name='{}_W'.format(self.name),
                                 regularizer=self.W_regularizer,
                                 constraint=self.W_constraint)

第一个参数加上shape

**Comment by zhouzuguang** [comment]
> Attention类实现感觉有问题,本人使用TextBiRNN模型来跑,出现以下错误:
> 
> Traceback (most recent call last):
>   File "train.py", line 86, in <module>
>     last_activation='softmax').get_model()
>   File "/media/gaoya/disk/Applications/keras/短文本分类/model.py", line 282, in get_model
>     x_word = Attention(self.maxlen_word)(x_word)
>   File "/media/gaoya/disk/Applications/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
>     return func(*args, **kwargs)
>   File "/media/gaoya/disk/Applications/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py", line 463, in __call__
>     self.build(unpack_singleton(input_shapes))
>   File "/media/gaoya/disk/Applications/keras/短文本分类/model.py", line 231, in build
>     constraint=self.b_constraint)
> TypeError: add_weight() got multiple values for argument 'name'
> 请问怎么解决呢

  self.W = self.add_weight(shape=(input_shape[-1], input_shape[-1],),
                                 initializer=self.init,
                                 name='{}_W'.format(self.name),
                                 regularizer=self.W_regularizer,
                                 constraint=self.W_constraint)
        if self.bias:
            self.b = self.add_weight(shape=(input_shape[-1],),
                                     initializer='zero',
                                     name='{}_b'.format(self.name),
                                     regularizer=self.b_regularizer,
                                     constraint=self.b_constraint)
第一个参数加上shape =

**Comment by Trevor4Y** [comment]
请问我试着输出了attention中与x相乘的那个a的值，但发现权值是我序列长度的平均只。比如我的输入每句话有23个词，然后每个权值都是1/23。。请问有遇到过类似的情况吗，或者这样的情况的原因可能是什么呢。。刚入门。。求解答，谢谢大佬~

**Comment by hfzi** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
MatthieuTexier, @unixfile, @yangtze1006, @thelyo, @myxvisual, @smartfish, @panickervinod, @seewhy163, @danieldietrich, @hsuanyuehpeng, @binury, @shove70, @thimper, @lukkonior, @0xanonff, @perezda, @cnheider, @juanfranblanco, @Bingnan, @alexyangfox, @LeoRoll, @kimbk79, @JungleCatSW, @kailinr, @andyhrchen, @MrShadowalker, @lannyyuan, @ChainlinkResources, @i-xiaov, @linagee, @serzhant, @daviddwlee84, @tzwlwm, @TBurchfield, @melg8, @Mrholiday45, @bitcoin-new, @xieyiwen, @alvinllim, @Dunlap28, @maxbitran, @keeganlee, @wedvjin, @cyl-e, @jimchang7, @dcharbon, @jingtying, @sharp0111, @jgm-learn, @cmcallisterReidDecentral, @Cryptocreatives, @SmartChainX, @JLospinoso, @Limitinit, @arhik, @martin75carames, @robertg, @AskyAdmin, @omid235, @leigaho, @uwstudent123, @wensontsai, @Zitrone44, @joelhandwell, @hyperwang, @syhd142, @ArtStealer, @iblus, @danoctavian, @pebble2015, @EnzanNoMetsuke, @plague85, @ankoehn, @fukkyy, @acid009, @Mafii, @soobing, @zicox, @pbuhrmann, @viranribic, @PegToken, @LeonZZhou, @adfelippe, @yuanchunfa, @hungtseyee, @UFOXD, @divraj, @k0dep, @hsen-dev, @danielwhitehall, @r1b, @like0403, @zxuanyu, @nthpower, @mmattioli, @Rekeams, @denisse-dev, @jmenglis, @Passw
